"""Task-owned SDK snapshot with serialized offer/answer platform operations.

Never edits the official reference. Run once, then flutter pub get --offline
inside the fixture. Cryptography and public packet formats remain unchanged.
"""
import hashlib
import argparse
import json
from pathlib import Path
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[4]
REFERENCE = ROOT.parent / 'client-sdk-flutter'
TARGET = ROOT / 'build-e2ee-backend/flutter-sdk-transport-v1'
FIXTURE = ROOT / 'tests/runtime/tools/media/flutter_e2ee_peer'


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    source = REFERENCE / 'lib/src/core/transport.dart'
    if subprocess.check_output(['git', '-C', str(REFERENCE), 'diff', 'HEAD', '--',
                                'lib/src/core/transport.dart']).strip():
        raise ValueError('reference transport differs from HEAD')
    if TARGET.exists() or (FIXTURE / 'pubspec_overrides.yaml').exists():
        raise ValueError('inspect existing derivative before preparing again')
    text = source.read_text(encoding='utf-8')
    replacements = [
        ('  Future<void> setRemoteDescription(rtc.RTCSessionDescription sd) async {', '''  // Serialize the complete asynchronous platform operation. A pending offer
  // must record renegotiate before a racing answer consumes that flag.
  Future<void> _signalOperations = Future<void>.value();
  Future<void> _serializeSignal(Future<void> Function() operation) {
    final result = _signalOperations.then((_) => operation());
    // Keep the lane usable after failure; callers still receive result's error.
    _signalOperations = result.then<void>((_) {}, onError: (Object error, StackTrace stack) {});
    return result;
  }

  Future<void> setRemoteDescription(rtc.RTCSessionDescription sd) =>
      _serializeSignal(() => _setRemoteDescription(sd));

  Future<void> _setRemoteDescription(rtc.RTCSessionDescription sd) async {'''),
        ('      await createAndSendOffer(); // await or un-awaited ?',
         '      await _createAndSendOffer(); // Already owns the serialized lane.'),
        ('  Future<void> createAndSendOffer([RTCOfferOptions? options]) async {',
         '''  Future<void> createAndSendOffer([RTCOfferOptions? options]) =>
      _serializeSignal(() => _createAndSendOffer(options));

  Future<void> _createAndSendOffer([RTCOfferOptions? options]) async {''')]
    for before, after in replacements:
        if text.count(before) != 1:
            raise ValueError('unexpected reference transport structure')
        text = text.replace(before, after)
    TARGET.mkdir()
    files = subprocess.check_output(['git', '-C', str(REFERENCE), 'ls-files',
        'lib', 'windows', 'shared_cpp', 'pubspec.yaml', 'LICENSE', 'README.md'], text=True).splitlines()
    originals = {}
    for name in files:
        original = REFERENCE / name
        if original.is_symlink() or not original.is_file():
            raise ValueError('unexpected reference file')
        destination = TARGET / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(original, destination)
        originals[name] = sha(original)
    patched = TARGET / 'lib/src/core/transport.dart'
    patched.write_text(text, encoding='utf-8', newline='\n')
    metadata = {
        'scope': 'task-owned Flutter SDK transport scheduling repair; not pristine official SDK',
        'reference_head': subprocess.check_output(['git', '-C', str(REFERENCE), 'rev-parse', 'HEAD'], text=True).strip(),
        'reference_files': originals,
        'transport_before_sha256': sha(source), 'transport_after_sha256': sha(patched),
        'tool_sha256': sha(Path(__file__)), 'crypto_changed': False}
    (TARGET / 'transport-provenance.json').write_text(json.dumps(metadata, indent=2), encoding='utf-8')
    (FIXTURE / 'pubspec_overrides.yaml').write_text(
        '# Generated by prepare_e2ee_flutter_transport.py; reference is read-only.\n'
        'dependency_overrides:\n  livekit_client:\n'
        '    path: ../../../../../build-e2ee-backend/flutter-sdk-transport-v1\n', encoding='utf-8')


def complete_windows():
    manifest = TARGET / 'transport-provenance.json'
    metadata = json.loads(manifest.read_text(encoding='utf-8'))
    if sha(TARGET / 'lib/src/core/transport.dart') != metadata['transport_after_sha256']:
        raise ValueError('transport input changed')
    if (TARGET / 'shared_cpp').exists():
        raise ValueError('Windows support already present')
    files = subprocess.check_output(['git', '-C', str(REFERENCE), 'ls-files', 'shared_cpp'], text=True).splitlines()
    for name in files:
        destination = TARGET / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(REFERENCE / name, destination)
        metadata['reference_files'][name] = sha(REFERENCE / name)
    metadata['windows_completion_tool_sha256'] = sha(Path(__file__))
    manifest.write_text(json.dumps(metadata, indent=2), encoding='utf-8')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--complete-windows', action='store_true')
    if parser.parse_args().complete_windows: complete_windows()
    else: main()
