# Validate against the repository's reviewed profile, not a self-asserted hash
# supplied only by the package. Usable with cmake -P for the integrity gate.
file(READ "${CMAKE_CURRENT_LIST_DIR}/../build/prepare/e2ee-backend-profile.json" e2ee_profile)
file(READ "${COHAVORA_E2EE_BACKEND_PACKAGE_DIR}/package.json" e2ee_package)
foreach(field package_id sdk_package_id upstream_commit)
    string(JSON e2ee_expected GET "${e2ee_profile}" "${field}")
    string(JSON e2ee_actual GET "${e2ee_package}" "${field}")
    if(NOT e2ee_actual STREQUAL e2ee_expected)
        message(FATAL_ERROR "E2EE backend package ${field} mismatch")
    endif()
endforeach()
string(JSON e2ee_count LENGTH "${e2ee_profile}" files)
math(EXPR e2ee_last "${e2ee_count} - 1")
foreach(index RANGE 0 ${e2ee_last})
    string(JSON e2ee_file MEMBER "${e2ee_profile}" files ${index})
    string(JSON e2ee_expected GET "${e2ee_profile}" files "${e2ee_file}")
    file(SHA256 "${COHAVORA_E2EE_BACKEND_PACKAGE_DIR}/${e2ee_file}" e2ee_actual)
    if(NOT e2ee_actual STREQUAL e2ee_expected)
        message(FATAL_ERROR "E2EE backend package input mismatch: ${e2ee_file}")
    endif()
endforeach()
file(READ "${CMAKE_CURRENT_LIST_DIR}/../build/prepare/webrtc-package.json" e2ee_sdk_profile)
foreach(config Debug Release)
    string(JSON e2ee_expected GET "${e2ee_sdk_profile}" configurations "${config}" library_sha256)
    file(SHA256 "${WEBRTC_ROOT}/lib/${config}/webrtc.lib" e2ee_actual)
    if(NOT e2ee_actual STREQUAL e2ee_expected)
        message(FATAL_ERROR "E2EE backend base SDK ${config} library mismatch")
    endif()
endforeach()
set(COHAVORA_E2EE_PATCH_DIR "${COHAVORA_E2EE_BACKEND_PACKAGE_DIR}/patched")
set(COHAVORA_E2EE_MEDIA_GUARD_DIR "${COHAVORA_E2EE_BACKEND_PACKAGE_DIR}/media-guard")
message(STATUS "E2EE native backend package and base SDK fingerprints verified")
