if(CPACK_BUILD_CONFIG AND NOT CPACK_BUILD_CONFIG STREQUAL "Release")
    string(APPEND CPACK_PACKAGE_FILE_NAME "-${CPACK_BUILD_CONFIG}")
endif()

if(CPACK_GENERATOR STREQUAL "NSIS")
    string(APPEND CPACK_PACKAGE_FILE_NAME "-Setup")
endif()
